org: carloslop0914
app: portfolio-api
service: portfolio-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment: 
    MONGODB_DATA_API_URL: ${param:mongodb-data-api-url}
    MONGODB_DATA_API_KEY: ${param:mongodb-data-api-key}
    MONGODB_DATA_SOURCE: ${param:data-source}
    DB_NAME: ${param:database-name}
    ASSETS_BUCKET: ${param:assets-bucket}
  httpApi:
    cors: true
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
      - "s3:PutObject"
      - "s3:GetObject"
      Resource: "arn:aws:s3:::${param:assets-bucket}/*"

functions:
  - ${file(./routes/functionsSpec.yml)}
  - ${file(./routes/projects.yml)}
  - ${file(./routes/assets.yml)}
  - ${file(./routes/technologies.yml)}

plugins:
  - serverless-offline
