org: carloslop0914
app: portfolio-api
service: portfolio-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment: 
    MONGODB_DATA_API_URL: ${param:mongodb-data-api-url}
    MONGODB_DATA_API_KEY: ${param:mongodb-data-api-key}
    MONGODB_DATA_SOURCE: ${param:data-source}
    DB_NAME: ${param:database-name}

functions:
  - ${file(./routes/functionsSpec.yml)}
  - ${file(./routes/projects.yml)}
